#Hotstring EndChars  
#Hotstring C o *                                                                 

; All greek symbols  - shortcut by their first two characters
::\al ::\alpha  
::\be ::\beta 
::\ga ::\gamma 
::\De ::\Delta 
::\de ::\delta 
::\ep ::\epsilon 
::\ze ::\zeta 
::\et ::\eta 
::\Th ::\Theta 
::\th ::\theta 
::\io ::\iota 
::\ka ::\kappa 
::\La ::\Lambda 
::\la ::\lambda 
::\mu ::\mu 
::\nu ::\nu 
::\Xi ::\Xi 
::\xi ::\xi 
::\Pi ::\Pi 
::\pi ::\pi 
::\va ::\varpi 
::\Si ::\Sigma 
::\si ::\sigma 
::\ta ::\tau 
::\Ph ::\Phi 
::\ph ::\phi 
::\va ::\varphi 
::\ch ::\chi 
::\Ps ::\Psi 
::\ps ::\psi 
::\Om ::\Omega 
::\om ::\omega 

::al ::\alpha 
::be ::\beta 
::ga ::\gamma 
::De ::\Delta 
::de ::\delta 
::ep ::\epsilon 
::ze ::\zeta 
::et ::\eta 
::Th ::\Theta 
::th ::\theta 
::io ::\iota 
::ka ::\kappa 
::La ::\Lambda 
::la ::\lambda 
::mu ::\mu 
::nu ::\nu 
::Xi ::\Xi 
::xi ::\xi 
::Pi ::\Pi 
::pi ::\pi 
::va ::\varpi 
::Si ::\Sigma 
::si ::\sigma 
::ta ::\tau 
::Ph ::\Phi 
::ph ::\phi 
::va ::\varphi 
::ch ::\chi 
::Ps ::\Psi 
::ps ::\psi 
::Om ::\Omega 
::om ::\omega